Repository jorgebucaran/fisher, pull requests merged in 2018-11, with the labels that each got.

#494 Optimize fisher startup path
  README.md
  fisher.fish
Labels: Breaking, Fix

#480 Read fishfile from $fisher_path instead of $fish_config
  fisher.fish
Labels: Fix

#495 docs: fix configuration commands
  README.md
Labels: Docs, Fix

#497 README: Update function option in conf.d
  README.md
Labels: Docs
