Repository jorgebucaran/fisher, pull requests merged in 2019-01, with the labels that each got.

#504 3.2.0
  README.md
  fisher.fish
Labels: Docs, Feature, Fix

#483 docs: Link to awesome-fish-shell list
  README.md
Labels: Docs

#516 Override fishfile content instead of replacing the file
  fisher.fish
Labels: Bug, Fix
